services:
  postgres:
    image: postgres:latest
    container_name: employee_service_db
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: employee_service_app
    restart: always
    environment:
      DATABASE_URL: ${DATABASE_URL}
      PORT: ${PORT}
    depends_on:
      - postgres
    ports:
      - "${PORT}:${PORT}"
    command: ["sh", "-c", "npx prisma migrate deploy && npm start"]

volumes:
  pgdata:
