FROM node:18-alpine as builder

WORKDIR /app

COPY package.json package-lock.json ./

RUN npm install --omit=dev  # Avoid installing unnecessary dev dependencies in production

COPY . .

RUN npx prisma generate

RUN npm run build

FROM node:18-alpine as runner

WORKDIR /app

COPY --from=builder /app /app

ENV NODE_ENV=production

EXPOSE 4000

CMD ["sh", "-c", "npx prisma migrate deploy && npm start"]
