services:
  feedback_service_db:
    image: mongo:latest
    container_name: feedback_service_db
    restart: always
    environment:
      MONGO_INITDB_DATABASE: ${DB_NAME}
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "27018:27017"
    volumes:
      - mongodata:/data/db

  feedback_service:
    build: .
    container_name: feedback_service_app
    restart: always
    environment:
      DATABASE_URL: ${DATABASE_URL}
      PORT: ${PORT}
    depends_on:
      - feedback_service_db
    ports:
      - "${PORT}:${PORT}"
    command: ["sh", "-c", "npm start"]

volumes:
  mongodata:
